spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: 9c63989b-b5c7-4593-a30d-9fa409f546ee
        # 禁用配置中心
      #        enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 9c63989b-b5c7-4593-a30d-9fa409f546ee