# mysql 自定义字段
DATABASE_IP: 192.168.37.10
DATABASE_PORT: 3306
DATABASE_NAME: oss_file_dev

spring:
  datasource:
    username: root
    password: 123456
  redis:
    username: root
    password: 123456
    database: 10
    host: ${DATABASE_IP}
    port: 6379


minio:
  bucket: loveverse
  endpoint: http://192.168.37.10:9000  #部署在docker上时，需填写对象存储上传的地址，9090是客户端地址
  access-key: qDNIisJ6FU1QQySSQva4 #账户
  secret-key: leG2OwjuC7PgBvFMJHuAnexl3J7e5sAcXIjqfENq #密码