spring:
  application:
    name: fast-gateway
  cloud:
    gateway:
      routes:
        #        - id: file-upload-service
        #          uri: lb://file-upload-service
        #          predicates:
        #            - Path=/file-upload-api/**
        #          filters:
        #            # 去除路径的第一部分
        #            - StripPrefix=1
        - id: wallpaper-web-service
          uri: lb://wallpaper-web-service
          predicates:
            - Path=/wallpaper-web-api/**
      #          filters:
      #            # 去除路径的第一部分
      #            - StripPrefix=1
      # 去重响应头中的Vary、Access-Control-Allow-Origin 和 Access-Control-Allow-Credentials 字段，保留第一个出现的值
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
    # v2.2.0版本需要开放9848和9849端口
    nacos:
      discovery:
        server-addr: 192.168.37.10:8848
      config:
        enabled: false
server:
  port: 30000
