spring:
  application:
    name: fast-gateway
  cloud:
    gateway:
      routes:
        - id: third_party_route
          uri:
            lb://oss-third-party
          predicates:
            - Path=/oss-third-party/oss-third-party/**
          filters:
            # 去除路径的第一部分
            - StripPrefix=1
      # 去重响应头中的Vary、Access-Control-Allow-Origin 和 Access-Control-Allow-Credentials 字段，保留第一个出现的值
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      # 禁用配置中心
      config:
        enabled: false

server:
  port: 88

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
#sa-token:
#  # token 名称（同时也是 cookie 名称）
#  token-name: LOVEVERSE-TOKEN
#  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
#  timeout: 2592000
#  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
#  active-timeout: -1
#  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
#  is-concurrent: true
#  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
#  is-share: true
#  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
#  token-style: uuid
#  # 是否输出操作日志
#  is-log: true
