# mysql配置
DATABASE_USERNAME: root
DATABASE_PASSWORD: 123456
DATABASE_IP: 192.168.37.10
DATABASE_PORT: 3306
DATABASE_NAME: wallpaper_web_dev

# redis配置
REDIS_HOST: 192.168.37.10
REDIS_PORT: 6379
REDIS_DB: 10
REDIS_PASSWORD: 123456


